name: Publish

on:
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[BUILD] | Install Dependencies'
        run: yarn install --frozen-lockfile
        shell: bash

      - name: '[BUILD] | Compile'
        run: yarn compile
        shell: bash

      - name: '[TEST] | Lint Check'
        run: yarn lint:check
        shell: bash

      - name: '[TEST] | Unit Tests'
        run: yarn test:unit --coverage
        shell: bash

      - name: '[TEST] | Integration Tests'
        run: yarn test:integration --coverage
        shell: bash

      - name: '[ACTION] | Clone publish npm action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/publish-npm-action
          ref: 4.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./publish-npm-action

      - name: '[ACTION] | Run publish npm action'
        uses: './publish-npm-action/application/github'
        with:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
